/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as MainRouteImport } from './routes/main'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as MainIndexRouteImport } from './routes/main.index'
import { Route as PortalWithdrawalRouteImport } from './routes/portal.withdrawal'
import { Route as PortalWalletEditRouteImport } from './routes/portal.wallet-edit'
import { Route as PortalTransactionsRouteImport } from './routes/portal.transactions'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalStakingPlansRouteImport } from './routes/portal.staking-plans'
import { Route as PortalStakingRouteImport } from './routes/portal.staking'
import { Route as PortalReferralRouteImport } from './routes/portal.referral'
import { Route as PortalQrCodeRouteImport } from './routes/portal.qr-code'
import { Route as PortalQnaRouteImport } from './routes/portal.qna'
import { Route as PortalPromotionRouteImport } from './routes/portal.promotion'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalNetworkRouteImport } from './routes/portal.network'
import { Route as PortalLandingPageRouteImport } from './routes/portal.landing-page'
import { Route as PortalKycRouteImport } from './routes/portal.kyc'
import { Route as PortalHoldingsRouteImport } from './routes/portal.holdings'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalDepositRouteImport } from './routes/portal.deposit'
import { Route as PortalChangePasswordRouteImport } from './routes/portal.change-password'
import { Route as MainStrategyRouteImport } from './routes/main.strategy'
import { Route as MainRoadmapRouteImport } from './routes/main.roadmap'
import { Route as MainNcoreRouteImport } from './routes/main.ncore'
import { Route as MainContactRouteImport } from './routes/main.contact'
import { Route as MainCollaborationRouteImport } from './routes/main.collaboration'
import { Route as MainCareersRouteImport } from './routes/main.careers'
import { Route as MainAboutRouteImport } from './routes/main.about'
import { Route as InviteMemberIdRouteImport } from './routes/invite.$memberId'
import { Route as PortalReportsIndexRouteImport } from './routes/portal.reports.index'
import { Route as PortalQnaIndexRouteImport } from './routes/portal.qna.index'
import { Route as PortalPromotionIndexRouteImport } from './routes/portal.promotion.index'
import { Route as PortalStatementUsdRouteImport } from './routes/portal.statement.usd'
import { Route as PortalStatementTransferUsdRouteImport } from './routes/portal.statement.transfer-usd'
import { Route as PortalStatementRewardsRouteImport } from './routes/portal.statement.rewards'
import { Route as PortalStatementCreditConversionRouteImport } from './routes/portal.statement.credit-conversion'
import { Route as PortalStatementConvertCreditsRouteImport } from './routes/portal.statement.convert-credits'
import { Route as PortalReportsTeamRewardsRouteImport } from './routes/portal.reports.team-rewards'
import { Route as PortalReportsStakingRouteImport } from './routes/portal.reports.staking'
import { Route as PortalReportsReferralRewardsRouteImport } from './routes/portal.reports.referral-rewards'
import { Route as PortalReportsParRankRewardsRouteImport } from './routes/portal.reports.par-rank-rewards'
import { Route as PortalReportsLeaderRewardsRouteImport } from './routes/portal.reports.leader-rewards'
import { Route as PortalReportsGlobalRewardsRouteImport } from './routes/portal.reports.global-rewards'
import { Route as PortalQnaMarketingRouteImport } from './routes/portal.qna.marketing'
import { Route as PortalQnaCompanyRouteImport } from './routes/portal.qna.company'
import { Route as PortalPromotionPromoIdRouteImport } from './routes/portal.promotion.$promoId'
import { Route as MainNcoreXRouteImport } from './routes/main.ncore.x'
import { Route as MainNcoreTrendsRouteImport } from './routes/main.ncore.trends'
import { Route as MainNcoreTradingRouteImport } from './routes/main.ncore.trading'
import { Route as MainNcoreTokenRouteImport } from './routes/main.ncore.token'
import { Route as MainNcoreFeaturesRouteImport } from './routes/main.ncore.features'
import { Route as MainNcoreBasicRouteImport } from './routes/main.ncore.basic'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const PortalWithdrawalRoute = PortalWithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWalletEditRoute = PortalWalletEditRouteImport.update({
  id: '/wallet-edit',
  path: '/wallet-edit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTransactionsRoute = PortalTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStakingPlansRoute = PortalStakingPlansRouteImport.update({
  id: '/staking-plans',
  path: '/staking-plans',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStakingRoute = PortalStakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReferralRoute = PortalReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQrCodeRoute = PortalQrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQnaRoute = PortalQnaRouteImport.update({
  id: '/qna',
  path: '/qna',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPromotionRoute = PortalPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNetworkRoute = PortalNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLandingPageRoute = PortalLandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => PortalRoute,
} as any)
const PortalKycRoute = PortalKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHoldingsRoute = PortalHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDepositRoute = PortalDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChangePasswordRoute = PortalChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => PortalRoute,
} as any)
const MainStrategyRoute = MainStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => MainRoute,
} as any)
const MainRoadmapRoute = MainRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => MainRoute,
} as any)
const MainNcoreRoute = MainNcoreRouteImport.update({
  id: '/ncore',
  path: '/ncore',
  getParentRoute: () => MainRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRoute,
} as any)
const MainCollaborationRoute = MainCollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => MainRoute,
} as any)
const MainCareersRoute = MainCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => MainRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any)
const InviteMemberIdRoute = InviteMemberIdRouteImport.update({
  id: '/invite/$memberId',
  path: '/invite/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalReportsIndexRoute = PortalReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQnaIndexRoute = PortalQnaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalQnaRoute,
} as any)
const PortalPromotionIndexRoute = PortalPromotionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalPromotionRoute,
} as any)
const PortalStatementUsdRoute = PortalStatementUsdRouteImport.update({
  id: '/statement/usd',
  path: '/statement/usd',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatementTransferUsdRoute =
  PortalStatementTransferUsdRouteImport.update({
    id: '/statement/transfer-usd',
    path: '/statement/transfer-usd',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalStatementRewardsRoute = PortalStatementRewardsRouteImport.update({
  id: '/statement/rewards',
  path: '/statement/rewards',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatementCreditConversionRoute =
  PortalStatementCreditConversionRouteImport.update({
    id: '/statement/credit-conversion',
    path: '/statement/credit-conversion',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalStatementConvertCreditsRoute =
  PortalStatementConvertCreditsRouteImport.update({
    id: '/statement/convert-credits',
    path: '/statement/convert-credits',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalReportsTeamRewardsRoute =
  PortalReportsTeamRewardsRouteImport.update({
    id: '/reports/team-rewards',
    path: '/reports/team-rewards',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalReportsStakingRoute = PortalReportsStakingRouteImport.update({
  id: '/reports/staking',
  path: '/reports/staking',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportsReferralRewardsRoute =
  PortalReportsReferralRewardsRouteImport.update({
    id: '/reports/referral-rewards',
    path: '/reports/referral-rewards',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalReportsParRankRewardsRoute =
  PortalReportsParRankRewardsRouteImport.update({
    id: '/reports/par-rank-rewards',
    path: '/reports/par-rank-rewards',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalReportsLeaderRewardsRoute =
  PortalReportsLeaderRewardsRouteImport.update({
    id: '/reports/leader-rewards',
    path: '/reports/leader-rewards',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalReportsGlobalRewardsRoute =
  PortalReportsGlobalRewardsRouteImport.update({
    id: '/reports/global-rewards',
    path: '/reports/global-rewards',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalQnaMarketingRoute = PortalQnaMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => PortalQnaRoute,
} as any)
const PortalQnaCompanyRoute = PortalQnaCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => PortalQnaRoute,
} as any)
const PortalPromotionPromoIdRoute = PortalPromotionPromoIdRouteImport.update({
  id: '/$promoId',
  path: '/$promoId',
  getParentRoute: () => PortalPromotionRoute,
} as any)
const MainNcoreXRoute = MainNcoreXRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => MainNcoreRoute,
} as any)
const MainNcoreTrendsRoute = MainNcoreTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => MainNcoreRoute,
} as any)
const MainNcoreTradingRoute = MainNcoreTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => MainNcoreRoute,
} as any)
const MainNcoreTokenRoute = MainNcoreTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => MainNcoreRoute,
} as any)
const MainNcoreFeaturesRoute = MainNcoreFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => MainNcoreRoute,
} as any)
const MainNcoreBasicRoute = MainNcoreBasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => MainNcoreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/invite/$memberId': typeof InviteMemberIdRoute
  '/main/about': typeof MainAboutRoute
  '/main/careers': typeof MainCareersRoute
  '/main/collaboration': typeof MainCollaborationRoute
  '/main/contact': typeof MainContactRoute
  '/main/ncore': typeof MainNcoreRouteWithChildren
  '/main/roadmap': typeof MainRoadmapRoute
  '/main/strategy': typeof MainStrategyRoute
  '/portal/change-password': typeof PortalChangePasswordRoute
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/kyc': typeof PortalKycRoute
  '/portal/landing-page': typeof PortalLandingPageRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/promotion': typeof PortalPromotionRouteWithChildren
  '/portal/qna': typeof PortalQnaRouteWithChildren
  '/portal/qr-code': typeof PortalQrCodeRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/staking': typeof PortalStakingRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/wallet-edit': typeof PortalWalletEditRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/main/': typeof MainIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/main/ncore/basic': typeof MainNcoreBasicRoute
  '/main/ncore/features': typeof MainNcoreFeaturesRoute
  '/main/ncore/token': typeof MainNcoreTokenRoute
  '/main/ncore/trading': typeof MainNcoreTradingRoute
  '/main/ncore/trends': typeof MainNcoreTrendsRoute
  '/main/ncore/x': typeof MainNcoreXRoute
  '/portal/promotion/$promoId': typeof PortalPromotionPromoIdRoute
  '/portal/qna/company': typeof PortalQnaCompanyRoute
  '/portal/qna/marketing': typeof PortalQnaMarketingRoute
  '/portal/reports/global-rewards': typeof PortalReportsGlobalRewardsRoute
  '/portal/reports/leader-rewards': typeof PortalReportsLeaderRewardsRoute
  '/portal/reports/par-rank-rewards': typeof PortalReportsParRankRewardsRoute
  '/portal/reports/referral-rewards': typeof PortalReportsReferralRewardsRoute
  '/portal/reports/staking': typeof PortalReportsStakingRoute
  '/portal/reports/team-rewards': typeof PortalReportsTeamRewardsRoute
  '/portal/statement/convert-credits': typeof PortalStatementConvertCreditsRoute
  '/portal/statement/credit-conversion': typeof PortalStatementCreditConversionRoute
  '/portal/statement/rewards': typeof PortalStatementRewardsRoute
  '/portal/statement/transfer-usd': typeof PortalStatementTransferUsdRoute
  '/portal/statement/usd': typeof PortalStatementUsdRoute
  '/portal/promotion/': typeof PortalPromotionIndexRoute
  '/portal/qna/': typeof PortalQnaIndexRoute
  '/portal/reports/': typeof PortalReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/invite/$memberId': typeof InviteMemberIdRoute
  '/main/about': typeof MainAboutRoute
  '/main/careers': typeof MainCareersRoute
  '/main/collaboration': typeof MainCollaborationRoute
  '/main/contact': typeof MainContactRoute
  '/main/ncore': typeof MainNcoreRouteWithChildren
  '/main/roadmap': typeof MainRoadmapRoute
  '/main/strategy': typeof MainStrategyRoute
  '/portal/change-password': typeof PortalChangePasswordRoute
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/kyc': typeof PortalKycRoute
  '/portal/landing-page': typeof PortalLandingPageRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/qr-code': typeof PortalQrCodeRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/staking': typeof PortalStakingRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/wallet-edit': typeof PortalWalletEditRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/main': typeof MainIndexRoute
  '/portal': typeof PortalIndexRoute
  '/main/ncore/basic': typeof MainNcoreBasicRoute
  '/main/ncore/features': typeof MainNcoreFeaturesRoute
  '/main/ncore/token': typeof MainNcoreTokenRoute
  '/main/ncore/trading': typeof MainNcoreTradingRoute
  '/main/ncore/trends': typeof MainNcoreTrendsRoute
  '/main/ncore/x': typeof MainNcoreXRoute
  '/portal/promotion/$promoId': typeof PortalPromotionPromoIdRoute
  '/portal/qna/company': typeof PortalQnaCompanyRoute
  '/portal/qna/marketing': typeof PortalQnaMarketingRoute
  '/portal/reports/global-rewards': typeof PortalReportsGlobalRewardsRoute
  '/portal/reports/leader-rewards': typeof PortalReportsLeaderRewardsRoute
  '/portal/reports/par-rank-rewards': typeof PortalReportsParRankRewardsRoute
  '/portal/reports/referral-rewards': typeof PortalReportsReferralRewardsRoute
  '/portal/reports/staking': typeof PortalReportsStakingRoute
  '/portal/reports/team-rewards': typeof PortalReportsTeamRewardsRoute
  '/portal/statement/convert-credits': typeof PortalStatementConvertCreditsRoute
  '/portal/statement/credit-conversion': typeof PortalStatementCreditConversionRoute
  '/portal/statement/rewards': typeof PortalStatementRewardsRoute
  '/portal/statement/transfer-usd': typeof PortalStatementTransferUsdRoute
  '/portal/statement/usd': typeof PortalStatementUsdRoute
  '/portal/promotion': typeof PortalPromotionIndexRoute
  '/portal/qna': typeof PortalQnaIndexRoute
  '/portal/reports': typeof PortalReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/main': typeof MainRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/invite/$memberId': typeof InviteMemberIdRoute
  '/main/about': typeof MainAboutRoute
  '/main/careers': typeof MainCareersRoute
  '/main/collaboration': typeof MainCollaborationRoute
  '/main/contact': typeof MainContactRoute
  '/main/ncore': typeof MainNcoreRouteWithChildren
  '/main/roadmap': typeof MainRoadmapRoute
  '/main/strategy': typeof MainStrategyRoute
  '/portal/change-password': typeof PortalChangePasswordRoute
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/kyc': typeof PortalKycRoute
  '/portal/landing-page': typeof PortalLandingPageRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/promotion': typeof PortalPromotionRouteWithChildren
  '/portal/qna': typeof PortalQnaRouteWithChildren
  '/portal/qr-code': typeof PortalQrCodeRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/staking': typeof PortalStakingRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/wallet-edit': typeof PortalWalletEditRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/main/': typeof MainIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/main/ncore/basic': typeof MainNcoreBasicRoute
  '/main/ncore/features': typeof MainNcoreFeaturesRoute
  '/main/ncore/token': typeof MainNcoreTokenRoute
  '/main/ncore/trading': typeof MainNcoreTradingRoute
  '/main/ncore/trends': typeof MainNcoreTrendsRoute
  '/main/ncore/x': typeof MainNcoreXRoute
  '/portal/promotion/$promoId': typeof PortalPromotionPromoIdRoute
  '/portal/qna/company': typeof PortalQnaCompanyRoute
  '/portal/qna/marketing': typeof PortalQnaMarketingRoute
  '/portal/reports/global-rewards': typeof PortalReportsGlobalRewardsRoute
  '/portal/reports/leader-rewards': typeof PortalReportsLeaderRewardsRoute
  '/portal/reports/par-rank-rewards': typeof PortalReportsParRankRewardsRoute
  '/portal/reports/referral-rewards': typeof PortalReportsReferralRewardsRoute
  '/portal/reports/staking': typeof PortalReportsStakingRoute
  '/portal/reports/team-rewards': typeof PortalReportsTeamRewardsRoute
  '/portal/statement/convert-credits': typeof PortalStatementConvertCreditsRoute
  '/portal/statement/credit-conversion': typeof PortalStatementCreditConversionRoute
  '/portal/statement/rewards': typeof PortalStatementRewardsRoute
  '/portal/statement/transfer-usd': typeof PortalStatementTransferUsdRoute
  '/portal/statement/usd': typeof PortalStatementUsdRoute
  '/portal/promotion/': typeof PortalPromotionIndexRoute
  '/portal/qna/': typeof PortalQnaIndexRoute
  '/portal/reports/': typeof PortalReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/main'
    | '/portal'
    | '/invite/$memberId'
    | '/main/about'
    | '/main/careers'
    | '/main/collaboration'
    | '/main/contact'
    | '/main/ncore'
    | '/main/roadmap'
    | '/main/strategy'
    | '/portal/change-password'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/kyc'
    | '/portal/landing-page'
    | '/portal/network'
    | '/portal/profile'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/qr-code'
    | '/portal/referral'
    | '/portal/staking'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/wallet-edit'
    | '/portal/withdrawal'
    | '/main/'
    | '/portal/'
    | '/main/ncore/basic'
    | '/main/ncore/features'
    | '/main/ncore/token'
    | '/main/ncore/trading'
    | '/main/ncore/trends'
    | '/main/ncore/x'
    | '/portal/promotion/$promoId'
    | '/portal/qna/company'
    | '/portal/qna/marketing'
    | '/portal/reports/global-rewards'
    | '/portal/reports/leader-rewards'
    | '/portal/reports/par-rank-rewards'
    | '/portal/reports/referral-rewards'
    | '/portal/reports/staking'
    | '/portal/reports/team-rewards'
    | '/portal/statement/convert-credits'
    | '/portal/statement/credit-conversion'
    | '/portal/statement/rewards'
    | '/portal/statement/transfer-usd'
    | '/portal/statement/usd'
    | '/portal/promotion/'
    | '/portal/qna/'
    | '/portal/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/invite/$memberId'
    | '/main/about'
    | '/main/careers'
    | '/main/collaboration'
    | '/main/contact'
    | '/main/ncore'
    | '/main/roadmap'
    | '/main/strategy'
    | '/portal/change-password'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/kyc'
    | '/portal/landing-page'
    | '/portal/network'
    | '/portal/profile'
    | '/portal/qr-code'
    | '/portal/referral'
    | '/portal/staking'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/wallet-edit'
    | '/portal/withdrawal'
    | '/main'
    | '/portal'
    | '/main/ncore/basic'
    | '/main/ncore/features'
    | '/main/ncore/token'
    | '/main/ncore/trading'
    | '/main/ncore/trends'
    | '/main/ncore/x'
    | '/portal/promotion/$promoId'
    | '/portal/qna/company'
    | '/portal/qna/marketing'
    | '/portal/reports/global-rewards'
    | '/portal/reports/leader-rewards'
    | '/portal/reports/par-rank-rewards'
    | '/portal/reports/referral-rewards'
    | '/portal/reports/staking'
    | '/portal/reports/team-rewards'
    | '/portal/statement/convert-credits'
    | '/portal/statement/credit-conversion'
    | '/portal/statement/rewards'
    | '/portal/statement/transfer-usd'
    | '/portal/statement/usd'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/reports'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/main'
    | '/portal'
    | '/invite/$memberId'
    | '/main/about'
    | '/main/careers'
    | '/main/collaboration'
    | '/main/contact'
    | '/main/ncore'
    | '/main/roadmap'
    | '/main/strategy'
    | '/portal/change-password'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/kyc'
    | '/portal/landing-page'
    | '/portal/network'
    | '/portal/profile'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/qr-code'
    | '/portal/referral'
    | '/portal/staking'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/wallet-edit'
    | '/portal/withdrawal'
    | '/main/'
    | '/portal/'
    | '/main/ncore/basic'
    | '/main/ncore/features'
    | '/main/ncore/token'
    | '/main/ncore/trading'
    | '/main/ncore/trends'
    | '/main/ncore/x'
    | '/portal/promotion/$promoId'
    | '/portal/qna/company'
    | '/portal/qna/marketing'
    | '/portal/reports/global-rewards'
    | '/portal/reports/leader-rewards'
    | '/portal/reports/par-rank-rewards'
    | '/portal/reports/referral-rewards'
    | '/portal/reports/staking'
    | '/portal/reports/team-rewards'
    | '/portal/statement/convert-credits'
    | '/portal/statement/credit-conversion'
    | '/portal/statement/rewards'
    | '/portal/statement/transfer-usd'
    | '/portal/statement/usd'
    | '/portal/promotion/'
    | '/portal/qna/'
    | '/portal/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MainRoute: typeof MainRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  InviteMemberIdRoute: typeof InviteMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/main/': {
      id: '/main/'
      path: '/'
      fullPath: '/main/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/portal/withdrawal': {
      id: '/portal/withdrawal'
      path: '/withdrawal'
      fullPath: '/portal/withdrawal'
      preLoaderRoute: typeof PortalWithdrawalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/wallet-edit': {
      id: '/portal/wallet-edit'
      path: '/wallet-edit'
      fullPath: '/portal/wallet-edit'
      preLoaderRoute: typeof PortalWalletEditRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/transactions': {
      id: '/portal/transactions'
      path: '/transactions'
      fullPath: '/portal/transactions'
      preLoaderRoute: typeof PortalTransactionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/staking-plans': {
      id: '/portal/staking-plans'
      path: '/staking-plans'
      fullPath: '/portal/staking-plans'
      preLoaderRoute: typeof PortalStakingPlansRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/staking': {
      id: '/portal/staking'
      path: '/staking'
      fullPath: '/portal/staking'
      preLoaderRoute: typeof PortalStakingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/referral': {
      id: '/portal/referral'
      path: '/referral'
      fullPath: '/portal/referral'
      preLoaderRoute: typeof PortalReferralRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/qr-code': {
      id: '/portal/qr-code'
      path: '/qr-code'
      fullPath: '/portal/qr-code'
      preLoaderRoute: typeof PortalQrCodeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/qna': {
      id: '/portal/qna'
      path: '/qna'
      fullPath: '/portal/qna'
      preLoaderRoute: typeof PortalQnaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/promotion': {
      id: '/portal/promotion'
      path: '/promotion'
      fullPath: '/portal/promotion'
      preLoaderRoute: typeof PortalPromotionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/network': {
      id: '/portal/network'
      path: '/network'
      fullPath: '/portal/network'
      preLoaderRoute: typeof PortalNetworkRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/landing-page': {
      id: '/portal/landing-page'
      path: '/landing-page'
      fullPath: '/portal/landing-page'
      preLoaderRoute: typeof PortalLandingPageRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/kyc': {
      id: '/portal/kyc'
      path: '/kyc'
      fullPath: '/portal/kyc'
      preLoaderRoute: typeof PortalKycRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/holdings': {
      id: '/portal/holdings'
      path: '/holdings'
      fullPath: '/portal/holdings'
      preLoaderRoute: typeof PortalHoldingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/deposit': {
      id: '/portal/deposit'
      path: '/deposit'
      fullPath: '/portal/deposit'
      preLoaderRoute: typeof PortalDepositRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/change-password': {
      id: '/portal/change-password'
      path: '/change-password'
      fullPath: '/portal/change-password'
      preLoaderRoute: typeof PortalChangePasswordRouteImport
      parentRoute: typeof PortalRoute
    }
    '/main/strategy': {
      id: '/main/strategy'
      path: '/strategy'
      fullPath: '/main/strategy'
      preLoaderRoute: typeof MainStrategyRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/roadmap': {
      id: '/main/roadmap'
      path: '/roadmap'
      fullPath: '/main/roadmap'
      preLoaderRoute: typeof MainRoadmapRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/ncore': {
      id: '/main/ncore'
      path: '/ncore'
      fullPath: '/main/ncore'
      preLoaderRoute: typeof MainNcoreRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/contact': {
      id: '/main/contact'
      path: '/contact'
      fullPath: '/main/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/collaboration': {
      id: '/main/collaboration'
      path: '/collaboration'
      fullPath: '/main/collaboration'
      preLoaderRoute: typeof MainCollaborationRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/careers': {
      id: '/main/careers'
      path: '/careers'
      fullPath: '/main/careers'
      preLoaderRoute: typeof MainCareersRouteImport
      parentRoute: typeof MainRoute
    }
    '/main/about': {
      id: '/main/about'
      path: '/about'
      fullPath: '/main/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRoute
    }
    '/invite/$memberId': {
      id: '/invite/$memberId'
      path: '/invite/$memberId'
      fullPath: '/invite/$memberId'
      preLoaderRoute: typeof InviteMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/reports/': {
      id: '/portal/reports/'
      path: '/reports'
      fullPath: '/portal/reports/'
      preLoaderRoute: typeof PortalReportsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/qna/': {
      id: '/portal/qna/'
      path: '/'
      fullPath: '/portal/qna/'
      preLoaderRoute: typeof PortalQnaIndexRouteImport
      parentRoute: typeof PortalQnaRoute
    }
    '/portal/promotion/': {
      id: '/portal/promotion/'
      path: '/'
      fullPath: '/portal/promotion/'
      preLoaderRoute: typeof PortalPromotionIndexRouteImport
      parentRoute: typeof PortalPromotionRoute
    }
    '/portal/statement/usd': {
      id: '/portal/statement/usd'
      path: '/statement/usd'
      fullPath: '/portal/statement/usd'
      preLoaderRoute: typeof PortalStatementUsdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/transfer-usd': {
      id: '/portal/statement/transfer-usd'
      path: '/statement/transfer-usd'
      fullPath: '/portal/statement/transfer-usd'
      preLoaderRoute: typeof PortalStatementTransferUsdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/rewards': {
      id: '/portal/statement/rewards'
      path: '/statement/rewards'
      fullPath: '/portal/statement/rewards'
      preLoaderRoute: typeof PortalStatementRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/credit-conversion': {
      id: '/portal/statement/credit-conversion'
      path: '/statement/credit-conversion'
      fullPath: '/portal/statement/credit-conversion'
      preLoaderRoute: typeof PortalStatementCreditConversionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/convert-credits': {
      id: '/portal/statement/convert-credits'
      path: '/statement/convert-credits'
      fullPath: '/portal/statement/convert-credits'
      preLoaderRoute: typeof PortalStatementConvertCreditsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/team-rewards': {
      id: '/portal/reports/team-rewards'
      path: '/reports/team-rewards'
      fullPath: '/portal/reports/team-rewards'
      preLoaderRoute: typeof PortalReportsTeamRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/staking': {
      id: '/portal/reports/staking'
      path: '/reports/staking'
      fullPath: '/portal/reports/staking'
      preLoaderRoute: typeof PortalReportsStakingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/referral-rewards': {
      id: '/portal/reports/referral-rewards'
      path: '/reports/referral-rewards'
      fullPath: '/portal/reports/referral-rewards'
      preLoaderRoute: typeof PortalReportsReferralRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/par-rank-rewards': {
      id: '/portal/reports/par-rank-rewards'
      path: '/reports/par-rank-rewards'
      fullPath: '/portal/reports/par-rank-rewards'
      preLoaderRoute: typeof PortalReportsParRankRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/leader-rewards': {
      id: '/portal/reports/leader-rewards'
      path: '/reports/leader-rewards'
      fullPath: '/portal/reports/leader-rewards'
      preLoaderRoute: typeof PortalReportsLeaderRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports/global-rewards': {
      id: '/portal/reports/global-rewards'
      path: '/reports/global-rewards'
      fullPath: '/portal/reports/global-rewards'
      preLoaderRoute: typeof PortalReportsGlobalRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/qna/marketing': {
      id: '/portal/qna/marketing'
      path: '/marketing'
      fullPath: '/portal/qna/marketing'
      preLoaderRoute: typeof PortalQnaMarketingRouteImport
      parentRoute: typeof PortalQnaRoute
    }
    '/portal/qna/company': {
      id: '/portal/qna/company'
      path: '/company'
      fullPath: '/portal/qna/company'
      preLoaderRoute: typeof PortalQnaCompanyRouteImport
      parentRoute: typeof PortalQnaRoute
    }
    '/portal/promotion/$promoId': {
      id: '/portal/promotion/$promoId'
      path: '/$promoId'
      fullPath: '/portal/promotion/$promoId'
      preLoaderRoute: typeof PortalPromotionPromoIdRouteImport
      parentRoute: typeof PortalPromotionRoute
    }
    '/main/ncore/x': {
      id: '/main/ncore/x'
      path: '/x'
      fullPath: '/main/ncore/x'
      preLoaderRoute: typeof MainNcoreXRouteImport
      parentRoute: typeof MainNcoreRoute
    }
    '/main/ncore/trends': {
      id: '/main/ncore/trends'
      path: '/trends'
      fullPath: '/main/ncore/trends'
      preLoaderRoute: typeof MainNcoreTrendsRouteImport
      parentRoute: typeof MainNcoreRoute
    }
    '/main/ncore/trading': {
      id: '/main/ncore/trading'
      path: '/trading'
      fullPath: '/main/ncore/trading'
      preLoaderRoute: typeof MainNcoreTradingRouteImport
      parentRoute: typeof MainNcoreRoute
    }
    '/main/ncore/token': {
      id: '/main/ncore/token'
      path: '/token'
      fullPath: '/main/ncore/token'
      preLoaderRoute: typeof MainNcoreTokenRouteImport
      parentRoute: typeof MainNcoreRoute
    }
    '/main/ncore/features': {
      id: '/main/ncore/features'
      path: '/features'
      fullPath: '/main/ncore/features'
      preLoaderRoute: typeof MainNcoreFeaturesRouteImport
      parentRoute: typeof MainNcoreRoute
    }
    '/main/ncore/basic': {
      id: '/main/ncore/basic'
      path: '/basic'
      fullPath: '/main/ncore/basic'
      preLoaderRoute: typeof MainNcoreBasicRouteImport
      parentRoute: typeof MainNcoreRoute
    }
  }
}

interface MainNcoreRouteChildren {
  MainNcoreBasicRoute: typeof MainNcoreBasicRoute
  MainNcoreFeaturesRoute: typeof MainNcoreFeaturesRoute
  MainNcoreTokenRoute: typeof MainNcoreTokenRoute
  MainNcoreTradingRoute: typeof MainNcoreTradingRoute
  MainNcoreTrendsRoute: typeof MainNcoreTrendsRoute
  MainNcoreXRoute: typeof MainNcoreXRoute
}

const MainNcoreRouteChildren: MainNcoreRouteChildren = {
  MainNcoreBasicRoute: MainNcoreBasicRoute,
  MainNcoreFeaturesRoute: MainNcoreFeaturesRoute,
  MainNcoreTokenRoute: MainNcoreTokenRoute,
  MainNcoreTradingRoute: MainNcoreTradingRoute,
  MainNcoreTrendsRoute: MainNcoreTrendsRoute,
  MainNcoreXRoute: MainNcoreXRoute,
}

const MainNcoreRouteWithChildren = MainNcoreRoute._addFileChildren(
  MainNcoreRouteChildren,
)

interface MainRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainCareersRoute: typeof MainCareersRoute
  MainCollaborationRoute: typeof MainCollaborationRoute
  MainContactRoute: typeof MainContactRoute
  MainNcoreRoute: typeof MainNcoreRouteWithChildren
  MainRoadmapRoute: typeof MainRoadmapRoute
  MainStrategyRoute: typeof MainStrategyRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainCareersRoute: MainCareersRoute,
  MainCollaborationRoute: MainCollaborationRoute,
  MainContactRoute: MainContactRoute,
  MainNcoreRoute: MainNcoreRouteWithChildren,
  MainRoadmapRoute: MainRoadmapRoute,
  MainStrategyRoute: MainStrategyRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface PortalPromotionRouteChildren {
  PortalPromotionPromoIdRoute: typeof PortalPromotionPromoIdRoute
  PortalPromotionIndexRoute: typeof PortalPromotionIndexRoute
}

const PortalPromotionRouteChildren: PortalPromotionRouteChildren = {
  PortalPromotionPromoIdRoute: PortalPromotionPromoIdRoute,
  PortalPromotionIndexRoute: PortalPromotionIndexRoute,
}

const PortalPromotionRouteWithChildren = PortalPromotionRoute._addFileChildren(
  PortalPromotionRouteChildren,
)

interface PortalQnaRouteChildren {
  PortalQnaCompanyRoute: typeof PortalQnaCompanyRoute
  PortalQnaMarketingRoute: typeof PortalQnaMarketingRoute
  PortalQnaIndexRoute: typeof PortalQnaIndexRoute
}

const PortalQnaRouteChildren: PortalQnaRouteChildren = {
  PortalQnaCompanyRoute: PortalQnaCompanyRoute,
  PortalQnaMarketingRoute: PortalQnaMarketingRoute,
  PortalQnaIndexRoute: PortalQnaIndexRoute,
}

const PortalQnaRouteWithChildren = PortalQnaRoute._addFileChildren(
  PortalQnaRouteChildren,
)

interface PortalRouteChildren {
  PortalChangePasswordRoute: typeof PortalChangePasswordRoute
  PortalDepositRoute: typeof PortalDepositRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalHoldingsRoute: typeof PortalHoldingsRoute
  PortalKycRoute: typeof PortalKycRoute
  PortalLandingPageRoute: typeof PortalLandingPageRoute
  PortalNetworkRoute: typeof PortalNetworkRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalPromotionRoute: typeof PortalPromotionRouteWithChildren
  PortalQnaRoute: typeof PortalQnaRouteWithChildren
  PortalQrCodeRoute: typeof PortalQrCodeRoute
  PortalReferralRoute: typeof PortalReferralRoute
  PortalStakingRoute: typeof PortalStakingRoute
  PortalStakingPlansRoute: typeof PortalStakingPlansRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalTransactionsRoute: typeof PortalTransactionsRoute
  PortalWalletEditRoute: typeof PortalWalletEditRoute
  PortalWithdrawalRoute: typeof PortalWithdrawalRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalReportsGlobalRewardsRoute: typeof PortalReportsGlobalRewardsRoute
  PortalReportsLeaderRewardsRoute: typeof PortalReportsLeaderRewardsRoute
  PortalReportsParRankRewardsRoute: typeof PortalReportsParRankRewardsRoute
  PortalReportsReferralRewardsRoute: typeof PortalReportsReferralRewardsRoute
  PortalReportsStakingRoute: typeof PortalReportsStakingRoute
  PortalReportsTeamRewardsRoute: typeof PortalReportsTeamRewardsRoute
  PortalStatementConvertCreditsRoute: typeof PortalStatementConvertCreditsRoute
  PortalStatementCreditConversionRoute: typeof PortalStatementCreditConversionRoute
  PortalStatementRewardsRoute: typeof PortalStatementRewardsRoute
  PortalStatementTransferUsdRoute: typeof PortalStatementTransferUsdRoute
  PortalStatementUsdRoute: typeof PortalStatementUsdRoute
  PortalReportsIndexRoute: typeof PortalReportsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalChangePasswordRoute: PortalChangePasswordRoute,
  PortalDepositRoute: PortalDepositRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalHoldingsRoute: PortalHoldingsRoute,
  PortalKycRoute: PortalKycRoute,
  PortalLandingPageRoute: PortalLandingPageRoute,
  PortalNetworkRoute: PortalNetworkRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalPromotionRoute: PortalPromotionRouteWithChildren,
  PortalQnaRoute: PortalQnaRouteWithChildren,
  PortalQrCodeRoute: PortalQrCodeRoute,
  PortalReferralRoute: PortalReferralRoute,
  PortalStakingRoute: PortalStakingRoute,
  PortalStakingPlansRoute: PortalStakingPlansRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalTransactionsRoute: PortalTransactionsRoute,
  PortalWalletEditRoute: PortalWalletEditRoute,
  PortalWithdrawalRoute: PortalWithdrawalRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalReportsGlobalRewardsRoute: PortalReportsGlobalRewardsRoute,
  PortalReportsLeaderRewardsRoute: PortalReportsLeaderRewardsRoute,
  PortalReportsParRankRewardsRoute: PortalReportsParRankRewardsRoute,
  PortalReportsReferralRewardsRoute: PortalReportsReferralRewardsRoute,
  PortalReportsStakingRoute: PortalReportsStakingRoute,
  PortalReportsTeamRewardsRoute: PortalReportsTeamRewardsRoute,
  PortalStatementConvertCreditsRoute: PortalStatementConvertCreditsRoute,
  PortalStatementCreditConversionRoute: PortalStatementCreditConversionRoute,
  PortalStatementRewardsRoute: PortalStatementRewardsRoute,
  PortalStatementTransferUsdRoute: PortalStatementTransferUsdRoute,
  PortalStatementUsdRoute: PortalStatementUsdRoute,
  PortalReportsIndexRoute: PortalReportsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MainRoute: MainRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  InviteMemberIdRoute: InviteMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
