/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalWithdrawalRouteImport } from './routes/portal.withdrawal'
import { Route as PortalTransactionsRouteImport } from './routes/portal.transactions'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalStakingPlansRouteImport } from './routes/portal.staking-plans'
import { Route as PortalReportsRouteImport } from './routes/portal.reports'
import { Route as PortalReferralRouteImport } from './routes/portal.referral'
import { Route as PortalQnaRouteImport } from './routes/portal.qna'
import { Route as PortalPromotionRouteImport } from './routes/portal.promotion'
import { Route as PortalPerformanceRouteImport } from './routes/portal.performance'
import { Route as PortalParticipationRouteImport } from './routes/portal.participation'
import { Route as PortalNetworkRouteImport } from './routes/portal.network'
import { Route as PortalHoldingsRouteImport } from './routes/portal.holdings'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalDepositRouteImport } from './routes/portal.deposit'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWithdrawalRoute = PortalWithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTransactionsRoute = PortalTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStakingPlansRoute = PortalStakingPlansRouteImport.update({
  id: '/staking-plans',
  path: '/staking-plans',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReferralRoute = PortalReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQnaRoute = PortalQnaRouteImport.update({
  id: '/qna',
  path: '/qna',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPromotionRoute = PortalPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPerformanceRoute = PortalPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalParticipationRoute = PortalParticipationRouteImport.update({
  id: '/participation',
  path: '/participation',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNetworkRoute = PortalNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHoldingsRoute = PortalHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDepositRoute = PortalDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/participation': typeof PortalParticipationRoute
  '/portal/performance': typeof PortalPerformanceRoute
  '/portal/promotion': typeof PortalPromotionRoute
  '/portal/qna': typeof PortalQnaRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/participation': typeof PortalParticipationRoute
  '/portal/performance': typeof PortalPerformanceRoute
  '/portal/promotion': typeof PortalPromotionRoute
  '/portal/qna': typeof PortalQnaRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/participation': typeof PortalParticipationRoute
  '/portal/performance': typeof PortalPerformanceRoute
  '/portal/promotion': typeof PortalPromotionRoute
  '/portal/qna': typeof PortalQnaRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/network'
    | '/portal/participation'
    | '/portal/performance'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/referral'
    | '/portal/reports'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/withdrawal'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/network'
    | '/portal/participation'
    | '/portal/performance'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/referral'
    | '/portal/reports'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/withdrawal'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/network'
    | '/portal/participation'
    | '/portal/performance'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/referral'
    | '/portal/reports'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/withdrawal'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/withdrawal': {
      id: '/portal/withdrawal'
      path: '/withdrawal'
      fullPath: '/portal/withdrawal'
      preLoaderRoute: typeof PortalWithdrawalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/transactions': {
      id: '/portal/transactions'
      path: '/transactions'
      fullPath: '/portal/transactions'
      preLoaderRoute: typeof PortalTransactionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/staking-plans': {
      id: '/portal/staking-plans'
      path: '/staking-plans'
      fullPath: '/portal/staking-plans'
      preLoaderRoute: typeof PortalStakingPlansRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports': {
      id: '/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/referral': {
      id: '/portal/referral'
      path: '/referral'
      fullPath: '/portal/referral'
      preLoaderRoute: typeof PortalReferralRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/qna': {
      id: '/portal/qna'
      path: '/qna'
      fullPath: '/portal/qna'
      preLoaderRoute: typeof PortalQnaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/promotion': {
      id: '/portal/promotion'
      path: '/promotion'
      fullPath: '/portal/promotion'
      preLoaderRoute: typeof PortalPromotionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/performance': {
      id: '/portal/performance'
      path: '/performance'
      fullPath: '/portal/performance'
      preLoaderRoute: typeof PortalPerformanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/participation': {
      id: '/portal/participation'
      path: '/participation'
      fullPath: '/portal/participation'
      preLoaderRoute: typeof PortalParticipationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/network': {
      id: '/portal/network'
      path: '/network'
      fullPath: '/portal/network'
      preLoaderRoute: typeof PortalNetworkRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/holdings': {
      id: '/portal/holdings'
      path: '/holdings'
      fullPath: '/portal/holdings'
      preLoaderRoute: typeof PortalHoldingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/deposit': {
      id: '/portal/deposit'
      path: '/deposit'
      fullPath: '/portal/deposit'
      preLoaderRoute: typeof PortalDepositRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalDepositRoute: typeof PortalDepositRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalHoldingsRoute: typeof PortalHoldingsRoute
  PortalNetworkRoute: typeof PortalNetworkRoute
  PortalParticipationRoute: typeof PortalParticipationRoute
  PortalPerformanceRoute: typeof PortalPerformanceRoute
  PortalPromotionRoute: typeof PortalPromotionRoute
  PortalQnaRoute: typeof PortalQnaRoute
  PortalReferralRoute: typeof PortalReferralRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalStakingPlansRoute: typeof PortalStakingPlansRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalTransactionsRoute: typeof PortalTransactionsRoute
  PortalWithdrawalRoute: typeof PortalWithdrawalRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDepositRoute: PortalDepositRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalHoldingsRoute: PortalHoldingsRoute,
  PortalNetworkRoute: PortalNetworkRoute,
  PortalParticipationRoute: PortalParticipationRoute,
  PortalPerformanceRoute: PortalPerformanceRoute,
  PortalPromotionRoute: PortalPromotionRoute,
  PortalQnaRoute: PortalQnaRoute,
  PortalReferralRoute: PortalReferralRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalStakingPlansRoute: PortalStakingPlansRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalTransactionsRoute: PortalTransactionsRoute,
  PortalWithdrawalRoute: PortalWithdrawalRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
