/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalWithdrawalRouteImport } from './routes/portal.withdrawal'
import { Route as PortalWalletEditRouteImport } from './routes/portal.wallet-edit'
import { Route as PortalTransactionsRouteImport } from './routes/portal.transactions'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalStakingPlansRouteImport } from './routes/portal.staking-plans'
import { Route as PortalReportsRouteImport } from './routes/portal.reports'
import { Route as PortalReferralRouteImport } from './routes/portal.referral'
import { Route as PortalQnaRouteImport } from './routes/portal.qna'
import { Route as PortalPromotionRouteImport } from './routes/portal.promotion'
import { Route as PortalParticipationRouteImport } from './routes/portal.participation'
import { Route as PortalNetworkRouteImport } from './routes/portal.network'
import { Route as PortalHoldingsRouteImport } from './routes/portal.holdings'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalDepositRouteImport } from './routes/portal.deposit'
import { Route as PortalAssetAnalysisRouteImport } from './routes/portal.asset-analysis'
import { Route as PortalStatementUsdRouteImport } from './routes/portal.statement.usd'
import { Route as PortalStatementTransferUsdRouteImport } from './routes/portal.statement.transfer-usd'
import { Route as PortalStatementRewardsRouteImport } from './routes/portal.statement.rewards'
import { Route as PortalStatementCreditConversionRouteImport } from './routes/portal.statement.credit-conversion'
import { Route as PortalStatementConvertCreditsRouteImport } from './routes/portal.statement.convert-credits'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWithdrawalRoute = PortalWithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWalletEditRoute = PortalWalletEditRouteImport.update({
  id: '/wallet-edit',
  path: '/wallet-edit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTransactionsRoute = PortalTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStakingPlansRoute = PortalStakingPlansRouteImport.update({
  id: '/staking-plans',
  path: '/staking-plans',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReferralRoute = PortalReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => PortalRoute,
} as any)
const PortalQnaRoute = PortalQnaRouteImport.update({
  id: '/qna',
  path: '/qna',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPromotionRoute = PortalPromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => PortalRoute,
} as any)
const PortalParticipationRoute = PortalParticipationRouteImport.update({
  id: '/participation',
  path: '/participation',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNetworkRoute = PortalNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHoldingsRoute = PortalHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDepositRoute = PortalDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAssetAnalysisRoute = PortalAssetAnalysisRouteImport.update({
  id: '/asset-analysis',
  path: '/asset-analysis',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatementUsdRoute = PortalStatementUsdRouteImport.update({
  id: '/statement/usd',
  path: '/statement/usd',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatementTransferUsdRoute =
  PortalStatementTransferUsdRouteImport.update({
    id: '/statement/transfer-usd',
    path: '/statement/transfer-usd',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalStatementRewardsRoute = PortalStatementRewardsRouteImport.update({
  id: '/statement/rewards',
  path: '/statement/rewards',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatementCreditConversionRoute =
  PortalStatementCreditConversionRouteImport.update({
    id: '/statement/credit-conversion',
    path: '/statement/credit-conversion',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalStatementConvertCreditsRoute =
  PortalStatementConvertCreditsRouteImport.update({
    id: '/statement/convert-credits',
    path: '/statement/convert-credits',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/asset-analysis': typeof PortalAssetAnalysisRoute
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/participation': typeof PortalParticipationRoute
  '/portal/promotion': typeof PortalPromotionRoute
  '/portal/qna': typeof PortalQnaRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/wallet-edit': typeof PortalWalletEditRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/statement/convert-credits': typeof PortalStatementConvertCreditsRoute
  '/portal/statement/credit-conversion': typeof PortalStatementCreditConversionRoute
  '/portal/statement/rewards': typeof PortalStatementRewardsRoute
  '/portal/statement/transfer-usd': typeof PortalStatementTransferUsdRoute
  '/portal/statement/usd': typeof PortalStatementUsdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal/asset-analysis': typeof PortalAssetAnalysisRoute
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/participation': typeof PortalParticipationRoute
  '/portal/promotion': typeof PortalPromotionRoute
  '/portal/qna': typeof PortalQnaRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/wallet-edit': typeof PortalWalletEditRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/portal': typeof PortalIndexRoute
  '/portal/statement/convert-credits': typeof PortalStatementConvertCreditsRoute
  '/portal/statement/credit-conversion': typeof PortalStatementCreditConversionRoute
  '/portal/statement/rewards': typeof PortalStatementRewardsRoute
  '/portal/statement/transfer-usd': typeof PortalStatementTransferUsdRoute
  '/portal/statement/usd': typeof PortalStatementUsdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/portal/asset-analysis': typeof PortalAssetAnalysisRoute
  '/portal/deposit': typeof PortalDepositRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/holdings': typeof PortalHoldingsRoute
  '/portal/network': typeof PortalNetworkRoute
  '/portal/participation': typeof PortalParticipationRoute
  '/portal/promotion': typeof PortalPromotionRoute
  '/portal/qna': typeof PortalQnaRoute
  '/portal/referral': typeof PortalReferralRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/staking-plans': typeof PortalStakingPlansRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/transactions': typeof PortalTransactionsRoute
  '/portal/wallet-edit': typeof PortalWalletEditRoute
  '/portal/withdrawal': typeof PortalWithdrawalRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/statement/convert-credits': typeof PortalStatementConvertCreditsRoute
  '/portal/statement/credit-conversion': typeof PortalStatementCreditConversionRoute
  '/portal/statement/rewards': typeof PortalStatementRewardsRoute
  '/portal/statement/transfer-usd': typeof PortalStatementTransferUsdRoute
  '/portal/statement/usd': typeof PortalStatementUsdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/portal/asset-analysis'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/network'
    | '/portal/participation'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/referral'
    | '/portal/reports'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/wallet-edit'
    | '/portal/withdrawal'
    | '/portal/'
    | '/portal/statement/convert-credits'
    | '/portal/statement/credit-conversion'
    | '/portal/statement/rewards'
    | '/portal/statement/transfer-usd'
    | '/portal/statement/usd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portal/asset-analysis'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/network'
    | '/portal/participation'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/referral'
    | '/portal/reports'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/wallet-edit'
    | '/portal/withdrawal'
    | '/portal'
    | '/portal/statement/convert-credits'
    | '/portal/statement/credit-conversion'
    | '/portal/statement/rewards'
    | '/portal/statement/transfer-usd'
    | '/portal/statement/usd'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/portal'
    | '/portal/asset-analysis'
    | '/portal/deposit'
    | '/portal/documents'
    | '/portal/holdings'
    | '/portal/network'
    | '/portal/participation'
    | '/portal/promotion'
    | '/portal/qna'
    | '/portal/referral'
    | '/portal/reports'
    | '/portal/staking-plans'
    | '/portal/support'
    | '/portal/transactions'
    | '/portal/wallet-edit'
    | '/portal/withdrawal'
    | '/portal/'
    | '/portal/statement/convert-credits'
    | '/portal/statement/credit-conversion'
    | '/portal/statement/rewards'
    | '/portal/statement/transfer-usd'
    | '/portal/statement/usd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/withdrawal': {
      id: '/portal/withdrawal'
      path: '/withdrawal'
      fullPath: '/portal/withdrawal'
      preLoaderRoute: typeof PortalWithdrawalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/wallet-edit': {
      id: '/portal/wallet-edit'
      path: '/wallet-edit'
      fullPath: '/portal/wallet-edit'
      preLoaderRoute: typeof PortalWalletEditRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/transactions': {
      id: '/portal/transactions'
      path: '/transactions'
      fullPath: '/portal/transactions'
      preLoaderRoute: typeof PortalTransactionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/staking-plans': {
      id: '/portal/staking-plans'
      path: '/staking-plans'
      fullPath: '/portal/staking-plans'
      preLoaderRoute: typeof PortalStakingPlansRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reports': {
      id: '/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/referral': {
      id: '/portal/referral'
      path: '/referral'
      fullPath: '/portal/referral'
      preLoaderRoute: typeof PortalReferralRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/qna': {
      id: '/portal/qna'
      path: '/qna'
      fullPath: '/portal/qna'
      preLoaderRoute: typeof PortalQnaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/promotion': {
      id: '/portal/promotion'
      path: '/promotion'
      fullPath: '/portal/promotion'
      preLoaderRoute: typeof PortalPromotionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/participation': {
      id: '/portal/participation'
      path: '/participation'
      fullPath: '/portal/participation'
      preLoaderRoute: typeof PortalParticipationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/network': {
      id: '/portal/network'
      path: '/network'
      fullPath: '/portal/network'
      preLoaderRoute: typeof PortalNetworkRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/holdings': {
      id: '/portal/holdings'
      path: '/holdings'
      fullPath: '/portal/holdings'
      preLoaderRoute: typeof PortalHoldingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/deposit': {
      id: '/portal/deposit'
      path: '/deposit'
      fullPath: '/portal/deposit'
      preLoaderRoute: typeof PortalDepositRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/asset-analysis': {
      id: '/portal/asset-analysis'
      path: '/asset-analysis'
      fullPath: '/portal/asset-analysis'
      preLoaderRoute: typeof PortalAssetAnalysisRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/usd': {
      id: '/portal/statement/usd'
      path: '/statement/usd'
      fullPath: '/portal/statement/usd'
      preLoaderRoute: typeof PortalStatementUsdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/transfer-usd': {
      id: '/portal/statement/transfer-usd'
      path: '/statement/transfer-usd'
      fullPath: '/portal/statement/transfer-usd'
      preLoaderRoute: typeof PortalStatementTransferUsdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/rewards': {
      id: '/portal/statement/rewards'
      path: '/statement/rewards'
      fullPath: '/portal/statement/rewards'
      preLoaderRoute: typeof PortalStatementRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/credit-conversion': {
      id: '/portal/statement/credit-conversion'
      path: '/statement/credit-conversion'
      fullPath: '/portal/statement/credit-conversion'
      preLoaderRoute: typeof PortalStatementCreditConversionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/statement/convert-credits': {
      id: '/portal/statement/convert-credits'
      path: '/statement/convert-credits'
      fullPath: '/portal/statement/convert-credits'
      preLoaderRoute: typeof PortalStatementConvertCreditsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAssetAnalysisRoute: typeof PortalAssetAnalysisRoute
  PortalDepositRoute: typeof PortalDepositRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalHoldingsRoute: typeof PortalHoldingsRoute
  PortalNetworkRoute: typeof PortalNetworkRoute
  PortalParticipationRoute: typeof PortalParticipationRoute
  PortalPromotionRoute: typeof PortalPromotionRoute
  PortalQnaRoute: typeof PortalQnaRoute
  PortalReferralRoute: typeof PortalReferralRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalStakingPlansRoute: typeof PortalStakingPlansRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalTransactionsRoute: typeof PortalTransactionsRoute
  PortalWalletEditRoute: typeof PortalWalletEditRoute
  PortalWithdrawalRoute: typeof PortalWithdrawalRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalStatementConvertCreditsRoute: typeof PortalStatementConvertCreditsRoute
  PortalStatementCreditConversionRoute: typeof PortalStatementCreditConversionRoute
  PortalStatementRewardsRoute: typeof PortalStatementRewardsRoute
  PortalStatementTransferUsdRoute: typeof PortalStatementTransferUsdRoute
  PortalStatementUsdRoute: typeof PortalStatementUsdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAssetAnalysisRoute: PortalAssetAnalysisRoute,
  PortalDepositRoute: PortalDepositRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalHoldingsRoute: PortalHoldingsRoute,
  PortalNetworkRoute: PortalNetworkRoute,
  PortalParticipationRoute: PortalParticipationRoute,
  PortalPromotionRoute: PortalPromotionRoute,
  PortalQnaRoute: PortalQnaRoute,
  PortalReferralRoute: PortalReferralRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalStakingPlansRoute: PortalStakingPlansRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalTransactionsRoute: PortalTransactionsRoute,
  PortalWalletEditRoute: PortalWalletEditRoute,
  PortalWithdrawalRoute: PortalWithdrawalRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalStatementConvertCreditsRoute: PortalStatementConvertCreditsRoute,
  PortalStatementCreditConversionRoute: PortalStatementCreditConversionRoute,
  PortalStatementRewardsRoute: PortalStatementRewardsRoute,
  PortalStatementTransferUsdRoute: PortalStatementTransferUsdRoute,
  PortalStatementUsdRoute: PortalStatementUsdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
